- operation: Add
  participant_description:
    name: AGV5
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.14999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV7
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.14999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV2
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.14999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV3
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.14999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV6
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.14999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV4
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.14999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV1
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.14999999999999999
        - 0.5