- operation: Add
  participant_description:
    name: AGV5
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV7
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV2
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV3
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV6
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV4
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV1
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV8
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV9
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV10
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV11
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV12
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV13
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV14
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV15
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV16
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV17
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV18
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV19
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5
- operation: Add
  participant_description:
    name: AGV20
    group: v1
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.29999999999999999
        - 0.5