robots:
  - namespace: AGV1
    initial_position:
      x: 162.60
      y: -44.40
  - namespace: AGV2
    initial_position:
      x: 162.60
      y: -52.65
  - namespace: AGV3
    initial_position:
      x: 162.60
      y: -60.90
  - namespace: AGV4
    initial_position:
      x: 162.60
      y: -69.2
  - namespace: AGV5
    initial_position:
      x: 162.60
      y: -77.45
  - namespace: AGV6
    initial_position:
      x: 162.60
      y: -85.7
  - namespace: AGV7
    initial_position:
      x: 162.60
      y: -93.95
  # Add more robots as needed
