# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "v1"
  fleet_manager:
    ip: "127.0.0.1"
    port: 22011
    user: "some_user"
    password: "some_password"
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.3 # radius in m
    vicinity: 0.5 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 # kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    finishing_request: "nothing" # [park, charge, nothing]

# TinyRobot CONFIG =================================================================

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for tinyRobot1
  AGV1:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV1"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV1"
  # Configuration for tinyRobot2
  AGV2:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV2"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV2"
  # Configuration for tinyRobot3
  AGV3:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV3"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV3"
  # Configuration for tinyRobot4
  AGV4:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV4"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV4"
  # Configuration for tinyRobot5
  AGV5:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV5"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV5"
  # Configuration for tinyRobot6
  AGV6:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV6"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV6"
  # Configuration for tinyRobot7
  AGV7:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV7"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV7"
  # Configuration for tinyRobot8
  AGV8:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV8"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV8"
  # Configuration for tinyRobot9
  AGV9:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV9"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV9"
  # Configuration for tinyRobot10
  AGV10:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV10"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV10"
  # Configuration for tinyRobot11
  AGV11:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV11"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV11"
  # Configuration for tinyRobot12
  AGV12:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV12"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV12"
  # Configuration for tinyRobot13
  AGV13:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV13"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV13"
  # Configuration for tinyRobot14
  AGV14:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV14"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV14"
  # Configuration for tinyRobot15
  AGV15:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV15"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV15"
  # Configuration for tinyRobot16
  AGV16:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV16"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV16"
  
  AGV17:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV17"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV17"
  AGV18:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV18"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV18"
  AGV19:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV19"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV19"
  AGV20:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "v2"
        waypoint: "AGV20"
        orientation: 0.0 # radians
      charger:
        waypoint: "AGV20"
